name: Build
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: yarn

    - name: Build pages
      env:
        NODE_ENV: production
      run: |
        yarn install
        yarn run export

    - name: Deploy pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: out
        publish_branch: gh-pages
        cname: flags.sh.cn
        user_name: GitHub Action
        user_email: action@github.com
